import { ProjectedArchitecture, ProjectedDiagram, DiagramNode } from '../pipeline/types.js';

const CATEGORY_FILL: Record<string, string> = {
  power: '#E6F4F1',
  control: '#DDF3F2',
  sensing: '#EAF7EC',
  storage: '#EEF1F8',
  connectivity: '#E8F0FE',
  audio: '#F3ECFA',
  ui: '#FFF4E5',
  haptic: '#FDECEC',
  gauge: '#F0F0F0',
  motor: '#FBE9E7',
  rail: '#019893',
};

const EDGE_COLOR: Record<string, string> = {
  power: '#075F69',
  rail: '#019893',
  i2c: '#9CD7D5',
  spi: '#F59E0B',
  uart: '#3B82F6',
  usb: '#021316',
  sdmmc: '#019893',
  signal: '#20E6E0',
  gpio: '#075F69',
  analog: '#EC4899',
};

const esc = (s: unknown): string =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const center = (n: DiagramNode) => ({ cx: n.x + n.w / 2, cy: n.y + n.h / 2 });

const renderDiagram = (d: ProjectedDiagram, offsetY: number): string => {
  const byId = new Map(d.nodes.map((n) => [n.id, n]));
  const parts: string[] = [];

  parts.push(`<g transform="translate(0,${offsetY})">`);
  parts.push(`<text x="20" y="28" font-size="18" font-weight="700" fill="#0f172a">${esc(d.title)}</text>`);
  if (d.caption) {
    parts.push(`<text x="20" y="48" font-size="11" fill="#475569">${esc(d.caption.slice(0, 160))}</text>`);
  }

  const body = 60;
  for (const e of d.edges) {
    const a = byId.get(e.from);
    const b = byId.get(e.to);
    if (!a || !b) continue;
    const { cx: x1, cy: y1 } = center(a);
    const { cx: x2, cy: y2 } = center(b);
    const color = EDGE_COLOR[e.type] ?? '#64748b';
    const dash = e.dashed ? ' stroke-dasharray="6 4"' : '';
    parts.push(
      `<line x1="${x1}" y1="${y1 + body}" x2="${x2}" y2="${y2 + body}" stroke="${color}" stroke-width="2"${dash} marker-end="url(#arrow)"/>`
    );
    if (e.label) {
      const mx = (x1 + x2) / 2;
      const my = (y1 + y2) / 2 + body - 4;
      parts.push(
        `<text x="${mx}" y="${my}" font-size="10" text-anchor="middle" fill="#334155" paint-order="stroke" stroke="#ffffff" stroke-width="3">${esc(e.label)}</text>`
      );
    }
  }

  for (const n of d.nodes) {
    const fill = CATEGORY_FILL[n.category] ?? '#f8fafc';
    const stroke = n.category === 'rail' ? '#019893' : '#075F69';
    parts.push(
      `<rect x="${n.x}" y="${n.y + body}" width="${n.w}" height="${n.h}" rx="8" ry="8" fill="${fill}" stroke="${stroke}" stroke-width="1.5"/>`
    );
    const { cx } = center(n);
    const labelY = n.y + body + n.h / 2 - (n.sublabel ? 4 : -4);
    parts.push(`<text x="${cx}" y="${labelY}" font-size="12" font-weight="600" text-anchor="middle" fill="#0f172a">${esc(n.label)}</text>`);
    if (n.sublabel) {
      parts.push(`<text x="${cx}" y="${labelY + 14}" font-size="10" text-anchor="middle" fill="#475569">${esc(n.sublabel)}</text>`);
    }
  }

  // Legend
  let lx = 20;
  const ly = body + d.height + 16;
  for (const item of d.legend) {
    parts.push(`<rect x="${lx}" y="${ly - 9}" width="12" height="12" rx="2" fill="${esc(item.color)}"/>`);
    parts.push(`<text x="${lx + 18}" y="${ly + 1}" font-size="11" fill="#334155">${esc(item.label)}</text>`);
    lx += 18 + Math.min(260, item.label.length * 6.5 + 24);
  }

  parts.push('</g>');
  return parts.join('\n');
};

/**
 * Renders the three projected diagrams (functional block, power tree, protocol map) into a single
 * standalone SVG document. Pure function of the persisted architecture — no network, no DB.
 */
export const renderArchitectureSvg = (arch: ProjectedArchitecture): string => {
  const diagrams = [arch.functionalBlock, arch.powerTree, arch.protocolMap].filter(Boolean);
  const blockHeight = (d: ProjectedDiagram) => d.height + 60 + 48;
  const width = Math.max(1000, ...diagrams.map((d) => d.width));
  const totalHeight = 60 + diagrams.reduce((acc, d) => acc + blockHeight(d), 0);

  const sections: string[] = [];
  let y = 60;
  for (const d of diagrams) {
    sections.push(renderDiagram(d, y));
    y += blockHeight(d);
  }

  const header = `<text x="20" y="34" font-size="22" font-weight="700" fill="#0f172a">${esc(arch.projectMeta.name)}</text>
<text x="20" y="52" font-size="12" fill="#475569">${esc(arch.projectMeta.tagline)} · Controller: ${esc(arch.projectMeta.controller)}${
    arch.versionTag ? ` · ${esc(arch.versionTag)}` : ''
  } · Generated by Embedo.ai</text>`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${totalHeight}" viewBox="0 0 ${width} ${totalHeight}" font-family="Inter, Helvetica, Arial, sans-serif">
<defs>
  <marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="#475569"/>
  </marker>
</defs>
<rect width="100%" height="100%" fill="#ffffff"/>
${header}
${sections.join('\n')}
</svg>`;
};
