-- Project titles were derived client-side from the first words of the raw intent text, so
-- abusive input surfaced verbatim as the project name. Titles are now generated by the
-- conversation router (Case F) and stored here.
ALTER TABLE "design_sessions" ADD COLUMN IF NOT EXISTS "title" VARCHAR(120);
